### PR TITLE
Wrapper script

### PR DESCRIPTION
**Pull request by ryanchild**

### CODE REVIEW

**Comment by ryanchild** [comment]
Ugh, sorry, don't merge this yet, I tried to be clever and pretty sure I created a bug where the segments can get out of order, will fix shortly

**Comment by mackworth** [comment]
Then two additional changes while you’re at it!

Due to the transition to Transport Stream, there’s a good chance you’ll get a file with no video stream.  It needs to report this to ctivo which will switch to TS and start all over again:

if [ -z "$video_stream"]; then
#probably PS stream; let cTiVo handle
    echo "no video streams"
    exit 1
fi

Secondly, the tmp directory name should have been based on $output, not $input.

Thx
H

**Comment by ryanchild** [comment]
Sure thing but I don't follow you on the tmpdir change.  $input is under /tmp/ctivo, $output is not?

**Comment by mackworth** [comment]
Indeed;  I meant that while the location of the directory should be based on the input file, the directory name should be based on the output file.  (output guaranteed to be a unique name, input is not).

--
Hugh Mackworth
701 Terrace Drive
Lake Oswego, OR
(503) 699-2134

**Comment by ryanchild** [comment]
Ah ok I see.  Fixed in the above commit, please go ahead and merge and make sure everything works with your test cases.

That's awesome that you were able to track down those bugs by the way, looking forward to being able to use this script in a format for all my recordings.  Thanks!

**Comment by mackworth** [comment]
So, the script merges the two directory names, which looks amusing, but not what we're looking for. I have updated.  Here's a compiled version for you to try out...

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

````
/Users/hugh/Library/Developer/Xcode/DerivedData/cTiVo-efjhciycmsjgiwduxrumsyrgqxji/Build/Products/Debug/cTiVo.app/Contents/MacOS/ffmpeg 
concat -safe 0 -i '/tmp/ctivo//Volumes/External/TivoShows/LBX- Little Battlers Experience- Operation- Covert Rescue-1_ffmpeg/ffmpeg_merge.txt' -map 0:0 -map 0:1 -c copy '/tmp/ctivo//Volumes/External/TivoShows/LBX- Little Battlers Experience- Operation- Covert Rescue-1_ffmpeg/logs/ffmpeg_concat.log'
````

**Comment by ryanchild** [comment]
Ha whoops, meant to do `$(dirname "$input")/$(basename "output")` but forgot the basename. 

Thanks for fixing, will test more when I get back in a few days.

**Pull request merged**
